### ISSUE TITLE
Difference between this package and unsetEventDispatcher()

### ISSUE THREAD

**Issue by qerim** [monooso/unobserve#1]
What is the difference between this and just doing `ModelName::unsetEventDispatcher();` ?

	// Check Dispatcher
	Model::getEventDispatcher()

	// Remove Dispatcher
	Model::unsetEventDispatcher()

	// Add Dispatcher
	Model::setEventDispatcher(new \Illuminate\Events\Dispatcher);

**Comment by monooso** [comment]
@qerim 

`unsetEventDispatcher` tells a specific model not to dispatch any events, to any listener (or observer). Unobserve (this package) tells a specific _observer_ not to handle any events.

Assume you have two model observers: one generates a UUID, the other performs Complex And Time-Consuming Operation™.

During testing (or even during normal code execution), you may wish to disable the latter, without affecting UUID generation.

Unobserve lets you do that.
